### ISSUE TITLE
Unable to get nested objects.

### ISSUE THREAD

**Issue by vincejairam** [byme8/Dapper.Json#2]
I can't seem to get this to work for nested objects e.g.

`{"isbn": "123-456-222",  
 "author": 
    {
      "lastname": "Doe",
      "firstname": "Jane"
    }
 }`

e.g. my parent object can get Book but can't get the author, its always null

`public class Test
{
public Json<Book> Data
}

public class Book
{
public string isbn { get; set; }
public Json<Author> author  { get; set; }
}

public class Author
{
public string lastname { get; set; }
public string firstname  { get; set; }
}
`

I'm I doing something wrong?

**Comment by byme8** [comment]
There is no need for the second `` Json<> `` inside the `` Book `` class. Replace `` Json<Author> `` with `` Author  ``
``` csharp
public class Test
{
     public Json<Book> Data
}

public class Book
{
     public string isbn { get; set; }
     public Author author { get; set; }
}

public class Author
{
     public string lastname { get; set; }
     public string firstname { get; set; }
}
```

**Comment by vincejairam** [comment]
I initially had it like this.. I removed the Json<> from Author and the author object is still null though. Is there something else that needs to be done?

**Comment by byme8** [comment]
How does SQL query look?

**Comment by byme8** [comment]
For me next query works as expected:
``` csharp
var connection = new SqlConnection(Config.ConnectionString);
var books = await connection.QueryAsync<Book>("""
                    SELECT 
                        ISBN,
                        (SELECT FirstName, LastName FROM Authors a where a.Id = b.AuthorEntityId  FOR JSON PATH, WITHOUT_ARRAY_WRAPPER) AS Author
                    FROM Books b
                 """);

foreach (var book in books)
{
    Console.WriteLine(book.ISBN);
    Console.WriteLine(book.Author.Value!.FirstName);
    Console.WriteLine(book.Author.Value!.LastName);
}
```

**Comment by vincejairam** [comment]
Ahhh this was driving me crazy, the issue was I forgot to add the  access modifier for the author field so by default it was private :(. once changed to public it all worked. Thanks for the help....
