### ISSUE TITLE
Returning result as Json causes it to be wrapper

### ISSUE THREAD

**Issue by Rudde** [byme8/Dapper.Json#4]
When obtaining an object using this method and the `Dapper.Json.Json<T>` wrapper the result in our API's will also have this wrapping. It will all be placed one level down under the key "Value".

Maybe the source generator could also generate that for a JsonConverter to unwrap these objects before serialization?

**Comment by Rudde** [comment]
Well that's why I use dapper. I'm not exposing my database model, I curate a query which I map to a custom DTO which is what I expose. If I exposed my database model I would just expose my EF model right out in the API, which isn't what I do, and it something different from what do. Change in query doesn't change API since I'm mapping it to a static model. A change to my DTO model would cause a change to the API model, but it's clearly the intention at that point. 

But we can even put all this aside. Since that isn't the only reason for serializing to json. And this is still an unintentional side-effect I would assume?

**Comment by byme8** [comment]
Looks like there is no need to add any source generator. You can just create your own JsonConveterFactory like that:
``` csharp

public class Program
{
    public static void Main()
    {
        var user = new UserData()
        {
            Emails = new Json<string[]>(Enumerable.Range(0, 10).Select(i => i.ToString()).ToArray())
        };

        var jsonSettings = new JsonSerializerOptions()
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            WriteIndented = true,
            Converters = { new JsonTConverterFactory() }
        };
        var json = JsonSerializer.Serialize(user, jsonSettings);
        Console.WriteLine(json);
    }
}

public class UserData
{
    public Json<string[]> Emails { get; set; }
}


public class JsonTConverterFactory : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert)
    {
        return typeToConvert.IsGenericType && typeToConvert.GetGenericTypeDefinition() == typeof(Json<>);
    }

    public override JsonConverter? CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        return Activator
            .CreateInstance(typeof(JsonTConverter<>)
                .MakeGenericType(typeToConvert.GetGenericArguments()[0])) as JsonConverter;
    }
}

public class JsonTConverter<T> : JsonConverter<Json<T>>
{
    public override Json<T> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = JsonSerializer.Deserialize<T>(ref reader, options);
        return new Json<T>(value);
    }

    public override void Write(Utf8JsonWriter writer, Json<T> value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value.Value, options);
    }
}
```
